import type { AuditAction, AuditTargetType } from './types';

export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  ADMIN_LOGIN: '어드민 로그인',
  ADMIN_CREATE: '어드민 계정 생성',
  ADMIN_UPDATE: '어드민 계정 수정',
  ADMIN_PASSWORD_RESET: '어드민 비밀번호 재설정',
  ADMIN_PASSWORD_CHANGE: '어드민 비밀번호 변경',
  USER_STATUS_UPDATE: '회원 상태 변경',
  USER_WITHDRAW: '회원 탈퇴 처리',
  USER_RESTORE: '회원 복구',
  NOTIFICATION_SEND: '알림 발송',
  NOTIFICATION_RESEND: '알림 재발송',
  NOTIFICATION_BROADCAST: '전체 알림 발송',
  SANCTION_CREATE: '제재 등록',
  SANCTION_REVOKE: '제재 철회',
  BAND_MASTER_TRANSFER: '밴드장 변경',
  BAND_INVITE_LINK_EXPIRE: '초대 링크 만료',
  BAND_DELETE: '밴드 삭제',
  BAND_RESTORE: '밴드 복구',
  GENRE_CREATE: '장르 생성',
  GENRE_UPDATE: '장르 수정',
  GENRE_DELETE: '장르 삭제',
  SKILL_TYPE_CREATE: '세션 생성',
  SKILL_TYPE_UPDATE: '세션 수정',
  SKILL_TYPE_DELETE: '세션 삭제',
  REPORT_RESOLVE: '신고 처리',
  ANNOUNCEMENT_CREATE: '공지 생성',
  ANNOUNCEMENT_UPDATE: '공지 수정',
  ANNOUNCEMENT_DELETE: '공지 삭제',
  SERVICE_SETTINGS_UPDATE: '서비스 설정 변경',
};

export const AUDIT_TARGET_TYPE_LABELS: Record<AuditTargetType, string> = {
  ADMIN: '어드민',
  USER: '회원',
  NOTIFICATION: '알림',
  SANCTION: '제재',
  BAND: '밴드',
  GENRE: '장르',
  SKILL_TYPE: '세션',
  REPORT: '신고',
  ANNOUNCEMENT: '공지',
  SERVICE_SETTINGS: '서비스 설정',
};
